CREATE TABLE IF NOT EXISTS storages (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_type VARCHAR(50) NOT NULL,
    bucket      VARCHAR(255) NOT NULL,
    path        VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_storage_type_bucket_path UNIQUE (storage_type, bucket, path)
);
