CREATE TABLE IF NOT EXISTS resources (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_key VARCHAR(255) NOT NULL,
    storage_type VARCHAR(50) NOT NULL,
    storage_bucket VARCHAR(255),
    storage_path VARCHAR(255)
);
